//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdus si
//     le code est regénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBasicServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://mc.com/webservices/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mc.com/webservices/", ConfigurationName="MyBasicServiceReference.MyBasicWebServiceSoap")]
    public interface MyBasicWebServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mc.com/webservices/Infos", ReplyAction="*")]
        System.Threading.Tasks.Task<MyBasicServiceReference.InfosResponse> InfosAsync(MyBasicServiceReference.InfosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mc.com/webservices/Data", ReplyAction="*")]
        System.Threading.Tasks.Task<MyBasicServiceReference.DataResponse> DataAsync(MyBasicServiceReference.DataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InfosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Infos", Namespace="http://mc.com/webservices/", Order=0)]
        public MyBasicServiceReference.InfosRequestBody Body;
        
        public InfosRequest()
        {
        }
        
        public InfosRequest(MyBasicServiceReference.InfosRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InfosRequestBody
    {
        
        public InfosRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InfosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InfosResponse", Namespace="http://mc.com/webservices/", Order=0)]
        public MyBasicServiceReference.InfosResponseBody Body;
        
        public InfosResponse()
        {
        }
        
        public InfosResponse(MyBasicServiceReference.InfosResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mc.com/webservices/")]
    public partial class InfosResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InfosResult;
        
        public InfosResponseBody()
        {
        }
        
        public InfosResponseBody(string InfosResult)
        {
            this.InfosResult = InfosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Data", Namespace="http://mc.com/webservices/", Order=0)]
        public MyBasicServiceReference.DataRequestBody Body;
        
        public DataRequest()
        {
        }
        
        public DataRequest(MyBasicServiceReference.DataRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DataRequestBody
    {
        
        public DataRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DataResponse", Namespace="http://mc.com/webservices/", Order=0)]
        public MyBasicServiceReference.DataResponseBody Body;
        
        public DataResponse()
        {
        }
        
        public DataResponse(MyBasicServiceReference.DataResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mc.com/webservices/")]
    public partial class DataResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MyBasicServiceReference.ArrayOfString DataResult;
        
        public DataResponseBody()
        {
        }
        
        public DataResponseBody(MyBasicServiceReference.ArrayOfString DataResult)
        {
            this.DataResult = DataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    public interface MyBasicWebServiceSoapChannel : MyBasicServiceReference.MyBasicWebServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    public partial class MyBasicWebServiceSoapClient : System.ServiceModel.ClientBase<MyBasicServiceReference.MyBasicWebServiceSoap>, MyBasicServiceReference.MyBasicWebServiceSoap
    {
        
        /// <summary>
        /// Implémentez cette méthode partielle pour configurer le point de terminaison de service.
        /// </summary>
        /// <param name="serviceEndpoint">Point de terminaison à configurer</param>
        /// <param name="clientCredentials">Informations d'identification du client</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MyBasicWebServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(MyBasicWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), MyBasicWebServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MyBasicWebServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MyBasicWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MyBasicWebServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MyBasicWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MyBasicWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyBasicServiceReference.InfosResponse> MyBasicServiceReference.MyBasicWebServiceSoap.InfosAsync(MyBasicServiceReference.InfosRequest request)
        {
            return base.Channel.InfosAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyBasicServiceReference.InfosResponse> InfosAsync()
        {
            MyBasicServiceReference.InfosRequest inValue = new MyBasicServiceReference.InfosRequest();
            inValue.Body = new MyBasicServiceReference.InfosRequestBody();
            return ((MyBasicServiceReference.MyBasicWebServiceSoap)(this)).InfosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyBasicServiceReference.DataResponse> MyBasicServiceReference.MyBasicWebServiceSoap.DataAsync(MyBasicServiceReference.DataRequest request)
        {
            return base.Channel.DataAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyBasicServiceReference.DataResponse> DataAsync()
        {
            MyBasicServiceReference.DataRequest inValue = new MyBasicServiceReference.DataRequest();
            inValue.Body = new MyBasicServiceReference.DataRequestBody();
            return ((MyBasicServiceReference.MyBasicWebServiceSoap)(this)).DataAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MyBasicWebServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.MyBasicWebServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Le point de terminaison nommé \'{0}\' est introuvable.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MyBasicWebServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44385/MyBasicWebService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.MyBasicWebServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44385/MyBasicWebService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Le point de terminaison nommé \'{0}\' est introuvable.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            MyBasicWebServiceSoap,
            
            MyBasicWebServiceSoap12,
        }
    }
}
